# Lifted from https://github.com/dlvhdr/gh-dash/blob/main/.goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/rimi-itk/gh-hmm
  mod: mod

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -tags=nodbus
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w
      - -X github.com/rimi-itk/gh-hmm/cmd.Version={{.Version}}
      - -X github.com/rimi-itk/gh-hmm/cmd.Commit={{.Commit}}
      - -X github.com/rimi-itk/gh-hmm/cmd.Date={{.CommitDate}}
      - -X github.com/rimi-itk/gh-hmm/cmd.BuiltBy=goreleaser

archives:
  - format: binary
    name_template: "gh-dash_{{ .Tag }}_{{ .Os }}-{{ .Arch }}{{if .Arm}}_{{.Arm}}{{end}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
